owner: licenseware
repo: uptime

sites:
  - name: Application - EU
    url: https://app.licenseware.io
    icon: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
  - name: Backend - EU
    url: https://api.licenseware.io/licenseware/
    icon: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
    expectedStatusCodes:
      - 200
      - 404
  - name: Application - US
    url: https://us.licenseware.io
    icon: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
  - name: Backend - US
    url: https://api.us.licenseware.io/licenseware/
    icon: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
    expectedStatusCodes:
      - 200
      - 404
  - name: Landing page
    url: https://licenseware.io
    icon: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
assignees:
  - meysam81
status-website:
  # cname: up.licenseware.io
  baseUrl: /uptime
  logoUrl: https://licenseware.io/wp-content/uploads/2020/11/cropped-Screenshot-2020-11-02-at-10.11.47.png
  name: Licenseware Uptime
  introTitle: Licenseware
  introMessage: The License Management App Ecosystem
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/licenseware/uptime
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/1 * * * *"
